Subo la tarea 1 con los cambios mencionados por Luis
lbenet/2022-1_TSFC3 pull request #17
Opened 2021-11-18 16:39 UTC by Andres-Carlos

Es la tarea 1 pero con los cambios mencionados por Luis exceptuando los cambios de la clase del dia de hoy (18/Nov) y sin el cambio en el modulo de la tarea 2.

2021-11-21 20:12 UTC, Julian-RC reviewed
Te envío la revisión de la tarea, algunos comentarios son muy fáciles de solucionar y te he indicado que agregar para su correcto funcionamiento. El punto clave es la definicón del intervalo vacío el cual seguro te hará agregar partes de código a las funciones ya existentes, Cualquier duda contactanos. Mañana te explico una cosa que creo que no tienes presente referente al import Base. Buen trabajo!

2021-11-21 20:12 UTC, Julian-RC commented on tareas/AndresCarlos/Tarea01.jl
> +
```suggestion
import Base: ⊆
```
Agrega esto para su correcto funcionamiento

2021-11-21 20:12 UTC, Julian-RC commented on tareas/AndresCarlos/Tarea01.jl
> +7 ∈ I2
```suggestion
```

2021-11-21 20:12 UTC, Julian-RC commented on tareas/AndresCarlos/Tarea01.jl
> +I1 == I2
```suggestion
```

2021-11-21 20:12 UTC, Julian-RC commented on tareas/AndresCarlos/Tarea01.jl
> +
```suggestion
import Base: ∩
```
Agrega

2021-11-21 20:12 UTC, Julian-RC commented on tareas/AndresCarlos/Tarea01.jl
> +
```suggestion
import Base: ∪
```

2021-11-30 06:34 UTC, Julian-RC commented
No hacemos comentarios acerca de la tarea pues se hicieron varios comentarios en la clase, en cuanto los tengas subelos y vamos analizando posibles errores al pasar los test. Mucha suerte !

2022-01-21 02:32 UTC, lbenet requested changes
Hay un punto muy importante: sólo se necesita que subas un archivo en este PR; sugiero que sea `tareas/AndresCarlos/Tarea1/intervalos.jl`, y que los demás archivos que incluiste los borres. Una vez dicho esto, dejé varios comentarios. Aunque algunos parecen triviales, resulta que al incluir cualquiera de los archivos `intervalos.jl` directamente en el REPL dan errores; los errores están relacionados con comentarios que empiezan con `#=` pero no hay `=#` que los termina, y quizás también con los `begin` y `end` superfluos. Cuando yo, localmente borro lo irreleante, los tests de la Tarea 1 pasan. Esto es, estás cerca de que el PR sea aceptado.

2022-01-21 02:32 UTC, lbenet commented on tareas/AndresCarlos/Tarea1/intervalos.jl
> +using InteractiveUtils
Estas líneas no son necesarias; las debes borrar.

2022-01-21 02:32 UTC, lbenet commented on tareas/AndresCarlos/Tarea1/intervalos.jl
> +# ╔═╡ 7dfae42a-4211-11ec-3983-29e1cea73a3b
Este tipo de comentarios son útiles para Pluto, pero no son necesarias aquí; si bien no es necesario que las borres, si lo puedes hacer, mejor.

2022-01-21 02:32 UTC, lbenet commented on tareas/AndresCarlos/Tarea1/intervalos.jl
> +begin
Todos los `begin` y sus `end` respectivos, los debes borrar. Por un lado, no aportan nada y sólo dificultan la lectura del código.

2022-01-21 02:32 UTC, lbenet commented on tareas/AndresCarlos/Tarea1/intervalos.jl
> +begin
De hecho, no me queda claro dónde está el `end` de este `begin`...

2022-01-21 02:32 UTC, lbenet commented on tareas/AndresCarlos/Tarea1/intervalos.jl
> +begin
Mismo comentario que arriba: borra los `begin` y sus `end`.

2022-01-21 02:32 UTC, lbenet commented on tareas/AndresCarlos/Tarea1/intervalos.jl
> +begin
No escribiré más sobre esto, pero el mismo comentario se aplica vasrias veces más abajo...

2022-01-21 02:32 UTC, lbenet commented on tareas/AndresCarlos/Tarea01.jl
> +
Este archivo no es necesario tenerlo en GitHub. Simplemente lo puedes borrar usando `git rm tareas/AndresCarlos/Tarea01.jl`, haciendo el commit necesario, y subiéndolo a GitHub.

2022-01-21 02:32 UTC, lbenet commented on tareas/AndresCarlos/Tarea1/intervalos.jl
> +# ╠═83d45aee-5241-4a98-9d7a-0eade42a71ef
Sugiero borrar todas estas líneas, ya que son sobras de lo que trabajaste en Pluto.

2022-01-21 02:32 UTC, lbenet commented on tareas/AndresCarlos/intervalos.jl
> +# v0.16.1
Los mismos comentarios que escribí para `tareas/AndresCarlos/Tarea1/intervalos.jl` se aplican a este archivo. No importa qué archivo, si este o `tareas/AndresCarlos/Tarea1/intervalos.jl`, sólo debes subir uno; yo sugiero que borres este, como expliqué en el comentario que dejé en `tareas/AndresCarlos/Tarea01.jl`.

2022-01-24 17:35 UTC, lbenet approved these changes
Todos los cambios requeridos se hicieron, y con la nueva versión los tests pasan!

2022-01-24 17:36 UTC, lbenet commented
El último commit hace que los tests pasen! Hago el merge!

2022-01-24 17:36 UTC, merged