Tutorial del manejo del curso en git
lbenet/2022-1_TSFC3 pull request #4
Opened 2021-09-27 08:10 UTC by Julian-RC

Agrego una primera versión del tutorial.

2021-09-27 19:10 UTC, lbenet requested changes
Gracias @Julian-RC por esta explicación! En general la veo muy bien, y lo único que hice fue indicar correcciones en la redacción o gramaticales/ortográficas que son fáciles de corregir.

2021-09-27 19:10 UTC, lbenet commented on clases/01-Git_tutorial.md
> +Ahora para subir avances  (yo realice un pequeño cambio en el archivo que subí) solo es necesario hacer un  `git add ...` y un `git commit ...` , realizas el `git push ....` igual que la vez anterior
realice -> realicé
solo -> sólo
"un `git commit ...` ," -> "un `git commit ...`),"
"`git push ...`" -> "`git push mifork_2 Tarea_1`,"
esta -> está

2021-09-27 19:10 UTC, lbenet commented on clases/01-Git_tutorial.md
> +Si miras el pull request que esta en el repositorio de la clase tiene dos commits sin necesidad de ir a la web y dar otro click!!. Lo que esto significa es que tu rama es el pull request, lo que haga
esta -> está
"Lo que esto significa es que tu rama es el pull request, lo que hagas ahí se  subirá como tarea cuando hasgas el push, por eso ten cuidado que editas :)" -> "Lo que esto significa es que tu rama es precisamente la actualización que se hace con el pull request al repositorio principal de la clase, con la consecuencia de que hagas ahí se  subirá como tarea al hacer el `push`, y por eso ten cuidado qué editas :smile:"

2021-09-27 19:10 UTC, lbenet commented on clases/01-Git_tutorial.md
> +- **DURANTE EL CURSO, CUANDO SE REVISEN LOS NOTEBOOK SIEMPRE SIEMPRE TRABAJEN EN RAMAS**, **NO TRABAJEN EN MAIN, NUNCA**.
Mismo comentario de negritas y mayúsculas.

2021-09-28 14:35 UTC, lbenet reviewed
Reenvío 4 comentarios con cuestiones ortográficas, que es todo lo que se requiere para aceptar el PR.

2021-09-28 14:35 UTC, lbenet commented on clases/01-Git_tutorial.md
> +Si miras el pull request que esta en el repositorio de la clase tiene dos commits sin necesidad de ir a la web y dar otro click!!. Lo que esto significa es que tu rama es precisamente la actualizació
esta -> está
"de que hagas ahí se" -> " de que lo que hagas ahí se"

2021-09-28 15:16 UTC, Julian-RC commented
Ya hice las correciones, no he agregado nada más.

2021-09-28 15:55 UTC, lbenet commented on clases/01-Git_tutorial.md
> +Y dentro de ésta copiarás el archivo con extensión .jl donde tienes tu tarea. **Ojo: no necesitamos ni los ipybn, ni .jpg, ni .png, etc. Que resultan como resultado de los ejercicios. Solo es necesar
Solo -> Sólo

2021-09-28 15:57 UTC, lbenet commented
Hay algunos cambios que sí veo en https://github.com/Julian-RC/2022-1_TSFC3/blob/tuto/clases/01-Git_tutorial.md pero que no veo reflejados aquí... Hiciste `git push`?

2021-09-28 16:11 UTC, Julian-RC commented
Yo sí veo los cambios, de hecho el archivo que citaste arriba es del primer commit.

2021-09-28 17:06 UTC, lbenet approved these changes

2021-09-28 17:07 UTC, lbenet commented
Hago el merge! Muchas gracias!

2021-09-28 17:07 UTC, merged